language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: home
      script:
        - bash ./buildapps/base.sh
        - bash ./buildapps/test.sh
        - cp -r build/ test
        - mv test/ build/
        - mv build ../
        - echo "excecuting next app"
        - cd ../covid19 # covid19app build
        - npm run build
        - cp -r build/ covid19
        - mv covid19 ../build/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
