language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd test
  - npm i
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: test/build
  on:
    branch: master
