language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: home
      script:
        - bash ./buildapps/env.sh
        - bash ./buildapps/base.sh
        - bash ./buildapps/test.sh
        - bash ./buildapps/covid19.sh
        - bash ./buildapps/timer.sh
        - bash ./buildapps/counter.sh
        - bash ./buildapps/githubcards.sh


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
