# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "Ajuajmal/react-things"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: master
    git: "github"
    stage: "clone"



  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: node:8.16 # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "bash tester.sh"
    environment:
      - CI=true
    stage: "test"


