# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: react-things-firebase CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: fire it
      run: bash builder.sh
    - name: install firebase
      run: npm i -g firebase-tools
    - name: config firebase
      run: firebase use react-things --token ${{ secrets.FIREBASE_TOKEN }}
    - name: deploy to firebase
      run: firebase deploy --only hosting -m "deploy from action" --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        CI: true
        react_app_homepage: ${{ secrets.react_app_homepage }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
